name: SneakyEnderPearlRide
version: 1.0
main: net.bappity.SneakyEnderPearlRide
api-version: '1.20'
commands:
  reloadsneaky:
    description: Reloads the configuration for SneakyEnderPearlRide.
    usage: /reloadsneaky