name: MyPlugin
version: 1.0
main: net.bappity.MyPlugin
api-version: '1.20'
commands:
  island:
    description: Generate a floating island
    usage: /island
  reloadsneaky:
    description: Reloads the configuration for MyPlugin.
    usage: /reloadsneaky