name: SneakyEnderPearlRide
version: 1.0
main: net.bappity.SneakyEnderPearlRide
api-version: '1.20'
commands:
  sneaky:
    description: Main command for the Sneak Ender Pearl Ride plugin
    usage: /sneaky <sub-command>
    permission: SneakyEnderPearlRide.use
    aliases: []